apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
  - name: app1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 15; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /randomshit
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: nfs