apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: hyperflow-engine
    component: hyperflow-engine
  name: hyperflow-config
data:
  job-template.yaml: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: job${jobName}
          spec:
            template:
              spec:
                restartPolicy: Never
                containers:
                - name: test
                  image: ${containerName}
                  env:
                    - name: HF_VAR_ENABLE_NETHOGS
                      value: "1"
                    - name: HF_VAR_WORK_DIR
                      value: "${volumePath}"
                    - name: HF_VAR_WAIT_FOR_INPUT_FILES
                      value: "0"
                    - name: HF_VAR_NUM_RETRIES
                      value: "1"
                    - name: HF_FS_MONIT_ENABLED
                      value: "1"
                    - name: HF_FS_MONIT_COMMAND
                      value: "${command}"
                    - name: HF_FS_MONIT_LOGFILE
                      value: "/fbam/file_access.log"
                    - name: HF_FS_MONIT_PATH_FILTER
                      value: "${volumePath}"
                  command:
                    - "/bin/sh"
                    - "-c"
                    - >
                      if [ $HF_FS_MONIT_ENABLED -eq 1 ]; then touch $HF_FS_MONIT_ENABLED ; LD_PRELOAD=/fbam/libfbam.so ${command}; exitCode=$? ; fi ;
                      if [ $HF_FS_MONIT_ENABLED -eq 0 ]; then ${command}; exitCode=$? ; fi ;
                      if [ $exitCode -ne 0 ]; then echo "Command ${command} returned exit code. $exitCode. Job fails." ; exit 1 ; fi ;
                  workingDir: ${volumePath}
                  resources:
                    requests:
                      cpu: ${cpuRequest}
                      memory: ${memRequest}
                  volumeMounts:
                  - name: my-pvc-nfs
                    mountPath: ${volumePath}
                volumes:
                - name: workflow-data
                  emptyDir: {}
                - name: my-pvc-nfs
                  persistentVolumeClaim:
                    claimName: nfs
