apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-deployment
  template:
    metadata:
      labels:
        name: demo-deployment
    spec:
      containers:
      - image: koxu1996/hyperflow
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        name: example
        volumeMounts:
          - name: my-pvc-nfs
            mountPath: "/opt/hfstorage"
      - image: redis
        name: redis
        ports:
          - name: redis
            containerPort: 6379
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
