apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster-1
  region: us-east-1

availabilityZones: ["us-east-1d",  "us-east-1f"]

nodeGroups:
  - name: hyperflow-engine
    labels: { nodetype: hfmaster }
    instanceType: m5.xlarge
    desiredCapacity: 1
  - name: hyperflow-worker-1
    labels: { nodetype: worker1 }
    instanceType: m5.xlarge
    desiredCapacity: 1
  - name: hyperflow-worker-2
    labels: { nodetype: worker2 }
    instanceType: m5a.xlarge
    desiredCapacity: 1
  # - name: hyperflow-worker-3
  #   labels: { nodetype: worker3 }
  #   instanceType: m5.xlarge
  #   desiredCapacity: 1
  # - name: hyperflow-worker-4
  #   labels: { nodetype: worker4 }
  #   instanceType: m5.xlarge
  #   desiredCapacity: 1