apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperflow-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperflow-engine 
  template:
    metadata:
      labels:
        name: hyperflow-engine
    spec:
      containers:
      - image: koxu1996/hyperflow
        env:
          - name: REDIS_URL
            value: redis://redis.default.svc.cluster.local:6379
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        name: example
        volumeMounts:
          - name: my-pvc-nfs
            mountPath: "/opt/hfstorage"
      - image: redis
        name: redis
        ports:
          - name: redis
            containerPort: 6379
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
