apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

kubectl cp montage-workflow $(kubectl get pods --selector=name=demo-deployment -o name | cut -d '/' -fls2):montage-workflow
kubectl cp montage-data $(kubectl get pods --selector=name=demo-deployment -o name | cut -d '/' -f2):/opt/hfstorage/
$ kubectl exec $(kubectl get pods --selector=name=demo-deployment -o name | cut -d '/' -f2) -- bash -c "mv /opt/hfstorage/montage-data/* /opt/hfstorage"