apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  template:
    metadata:
      labels:
        component: {{ include "common.names.fullname" . }}
        name: {{ include "common.names.fullname" . }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      volumes: {{- .Values.volumes | toYaml | nindent 6 }}
      containers:
		    - name: {{ include "common.names.fullname" . }}
		      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
		      imagePullPolicy: {{ .Values.image.pullPolicy }}
		      resources: {{- .Values.resources | toYaml | nindent 8 }}
		      volumeMounts: {{- .Values.volumeMounts | toYaml | nindent 8 }}
		      env: {{- .Values.parser.env | toYaml | nindent 8 }}
		      command: {{- .Values.parser.command | toYaml | nindent 8 }}
