apiVersion: batch/v1
kind: Job
metadata:
  name: logs-parser
spec:
  template:
    metadata:
      labels:
        component: logs-parser
        name: logs-parser
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      	command: {{ .Values.container.command | toYaml | nindent 8 }}
        resources: {{- .Values.resources | toYaml | nindent 8 }}	
        volumeMounts: {{- .Values.container.volumeMounts | toYaml | nindent 8 }}
      restartPolicy: {{- .Values.restartPolicy }}
      volumes: {{- .Values.volumes | toYaml | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8}}
      {{- end }}