apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ include "common.names.fullname" . }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: {{ include "common.names.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8}}
      {{- end }}