apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  ports:
  - name: {{ include "common.names.fullname" . }}
    port: {{ .Values.container.port }}
    targetPort: {{ include "common.names.fullname" . }}
  selector:
    name: {{ include "common.names.fullname" . }}
