# Default values for fbam-parser.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: "fbam-parser"

image:
  repository: cano601/fbam-log-parser
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

restartPolicy: Never
  
resources:
	requests:
		cpu: 0
		
volumeMounts:
- mountPath: /work_dir:shared
  name: workflow-data

volumes:
- name: workflow-data
  persistentVolumeClaim:
    claimName: nfs
    
parser:
	command:	
		- /bin/bash
		- -c
		- 'while ! [ -f /work_dir/postprocStart ]; do echo "Waiting for postprocStart
		  flag to be mounted..." ; sleep 5 ; done ; echo "postprocStart flag mounted:
		  " ;  mkdir -p "$FBAM_LOGS_TARGET_DIR" ; /log_parser.sh ;

		  '
  env:  
    - name: FBAM_LOGS_SOURCE_PATTERN
      value: /work_dir/logs-hf/*
    - name: FBAM_LOGS_TARGET_DIR
      value: /work_dir/fbam_parsed
    - name: FBAM_LOGS_SOURCE_FILE_REGEX
      value: ^.*_([a-zA-Z0-9]+_[0-9])+_([0-9]+)_[0-9]+.jsonl$
