apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      role: {{ include "common.names.fullname" . }}-server
  template:
    metadata:
      labels:
        role: {{ include "common.names.fullname" . }}-server
    spec:
      containers:
        - name: {{ include "common.names.fullname" . }}-server
          image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
          command: {{ .Values.serverContainer.command | toYaml | nindent 8 }}
          ports: {{ .Values.serverContainer.ports | toYaml | nindent 8 }}
          securityContext: {{ .Values.serverContainer.securityContext | toYaml | nindent 8 }}
          volumeMounts: {{ .Values.volumeMounts | toYaml | nindent 8 }}
        - name: {{ .Values.workflowDataContainer.name }}
          image: {{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag }}
          imagePullPolicy: {{ .Values.workflow.image.pullPolicy}}
          command: {{ .Values.workflowContainer.command | toYaml | nindent 8 }}
          securityContext: {{- .Values.securityContext | toYaml | nindent 8 }}
          lifecycle: {{- .Values.workflowDataContainer.lifecycle | toYaml | nindent 8 }}
          volumeMounts: {{- .Values.volumeMounts | toYaml | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8}}
      {{- end }}
      volumes: {{ .Values.volumes | toYaml | nindent 8}}
      