apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  accessModes: {{ .Values.pv.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pv.capacity.storage }}
  storageClassName: {{ .Values.pv.storageClassName }}
