apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  template:
    metadata:
      labels:
        component: {{ include "common.names.fullname" . }}
        name: {{ include "common.names.fullname" . }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      securityContext: {{- .Values.securityContext | toYaml | nindent 8 }}
      containers:
      - name: {{ .Values.container.name }}
      	image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      	command: {{- .Values.container.command | toYaml | nindent 8 }}
        env: {{- .Values.container.env | toYaml | nindent 8 }}
        resources: {{- .Values.resources | toYaml | nindent 8 }}
        volumeMounts: {{- .Values.container.volumeMounts | toYaml | nindent 8 }}
      volumes: {{- .Values.volumes | toYaml | nindent 8 }}
